apiVersion: v1
kind: Service
metadata:
  name: nodejs-backend-app-service
spec:
  selector:
    app: nodejs-backend-app
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
  type: LoadBalancer
        

